### ISSUE TITLE
Issue with official 5.4 release

### ISSUE THREAD

**Issue by mikec316** [Nebukam/PCGExtendedToolkit#39]
![image](https://github.com/Nebukam/PCGExtendedToolkit/assets/55247752/b9f5163f-9365-4ca2-83d2-a22f424eb643)

Hey, I hope you're well! 

There is some sort of symbol error causing build to fail on the official 5.4 release. 

Regards,

Mike

**Comment by Nebukam** [comment]
Hey @mikec316! Will try looking at this this upcoming weekend, sorry it can't be sooner :(

**Comment by mikec316** [comment]
Hey,

No worries on the timeline, thanks for letting me know.

Mike

**Comment by Nebukam** [comment]
Pushed an update!

**Comment by mikec316** [comment]
Thank you!
