### ISSUE TITLE
linux build issue

### ISSUE THREAD

**Issue by tychotic** [Nebukam/PCGExtendedToolkit#44]
Received this error building for linux. Is it a known issue? Any reason not to make the fix suggested in the error messsage? ("use reference type...") 

^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
[144/169] Compile Module.ShooterCoreRuntime.cpp
[145/169] Compile Module.PCGExtendedToolkit.6.cpp
In file included from /src/game/Plugins/PCGExtendedToolkit/Intermediate/Build/Linux/x64/UnrealEditor/Development/PCGExtendedToolkit/Module.PCGExtendedToolkit.6.cpp:30:
/src/game/Plugins/PCGExtendedToolkit/Source/PCGExtendedToolkit/Private/Data/PCGExGraphDefinition.cpp:248:33: error: loop variable 'Socket' creates a copy from type 'const PCGExGraph::FSocket' [-Werror,-Wrange-loop-construct]
for (const PCGExGraph::FSocket Socket : SocketMapping->Sockets)
^
/src/game/Plugins/PCGExtendedToolkit/Source/PCGExtendedToolkit/Private/Data/PCGExGraphDefinition.cpp:248:7: note: use reference type 'const PCGExGraph::FSocket &' to prevent copying
for (const PCGExGraph::FSocket Socket : SocketMapping->Sockets)
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
&

**Comment by Nebukam** [comment]
Hey @tychotic ! Nope, never tried to compile on Linux, but the error is clearly an oversight on my part; no idea why Rider didn't catch it since it's usually keen on that kind of stuff :/

Thanks for the report <3

**Comment by tychotic** [comment]
Thanks for the fast fix!! Huge fan, learning a lot from your code here.
