### ISSUE TITLE
linux editor build can't find include "PCGExPathfindingGrowPaths.h'"

### ISSUE THREAD

**Issue by tychotic** [Nebukam/PCGExtendedToolkit#45]
This builds fine on Windows + Server. It's failing on editor on linux.

I looked at the include line in PCGExPathfindingGrowPaths.cpp and it was using a different include style, so maybe a temp issue?

Note also that it's not just "..GrowPaths.cpp," but also an include from Module.PCGExtendedToolkit.7.cpp, which looks generated...

Error below. Thanks for all the great code.

- Matt

[143/169] Compile Module.PCGExtendedToolkit.7.cpp
In file included from /src/game/Plugins/PCGExtendedToolkit/Intermediate/Build/Linux/x64/UnrealEditor/Development/PCGExtendedToolkit/Module.PCGExtendedToolkit.7.cpp:18:
/src/game/Plugins/PCGExtendedToolkit/Source/PCGExtendedToolkit/Private/Graph/Pathfinding/PCGExPathfindingGrowPaths.cpp:4:10: fatal error: '..\..\..\Public\Graph\Pathfinding\PCGExPathfindingGrowPaths.h' file not found
#include "..\..\..\Public\Graph\Pathfinding\PCGExPathfindingGrowPaths.h"
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

**Comment by Nebukam** [comment]
Ah yes, that's Rider messing up import when you rename a file, and since they're collapsed I never noticed... Sorry about that >.<

**Comment by tychotic** [comment]
omg wow fast thanks!
