### ISSUE TITLE
findcontours only returning one path for multiple seeds?

### ISSUE THREAD

**Issue by tychotic** [Nebukam/PCGExtendedToolkit#50]
I seem to be only getting one path back (it's a nice one) from findcountours when I am passing in multiple seeds. Should we not see multiple paths coming out? Very likely user error, still learning this system.

**Comment by tychotic** [comment]
Also, I am using findcontours to recover the 2d hull around each seed in a voronoi graph. I assume this is a canonical use? I tried to extract individual hulls from the voronoi directly but not clear how to.

**Comment by Nebukam** [comment]
So, it's indeed the canonical way of getting the Voronoi cells! (if there is one ahah) -- however the findcountours suffers from some legacy code, I'll update ASAP to have a single target input, with each individual point being a seed.

At the moment, it's using collections as seed, which is bad. You basically need to create individual partitions from your points in order for them to act as individual seeds. I added an example in the example project (EdgesAndGraphs/FubdVoronoiCellContours)
![image](https://github.com/Nebukam/PCGExtendedToolkit/assets/5935407/104ae8eb-a288-4536-9589-6e1e009ede7a)

However as you can see, some contours are picked on the wrong side: it looks like some seeds are missing their associated contour, but it's in fact creating duplicate contours from neighboring cells >.<

**Comment by Nebukam** [comment]
So bottom line: your approach is the right one, I'm the one who fucked up.

**Comment by tychotic** [comment]
haha so it was good input I'm happy thanks again

I thought it was *partion*something

**Comment by tychotic** [comment]
user error, better version coming anyway :D
