### ISSUE TITLE
Shipping build issues

### ISSUE THREAD

**Issue by paulash** [Nebukam/PCGExtendedToolkit#53]
There are a number of issues with shipping builds, starting with 'settings' is a non-redistributable module. There are a handful of function declaration that are opt'd out without editor, but the definition is not, and there are many many usages of FORCEINLINE that are incorrectly defined and break with shipping builds.

**Comment by Nebukam** [comment]
Will look into this, thanks!
What platform are you on?

**Comment by paulash** [comment]
Win64, but these issues would effect shipping on any platform.

**Comment by Nebukam** [comment]
Not to state the obvious but it's been a while o haven't sanity checked with shipping; sorry about that 😅

**Comment by paulash** [comment]
Understandable; not really meant for production, just ran into issues when we started using our build server to run test cases.

**Comment by Nebukam** [comment]
I think I fixed all of the issues on the cluster-feature branch; I was able to package a build locally without warning nor errors -- HOWEVER, this branch contains a very large number of breaking updates, is not bug-free when it comes to some nodes.
I've been doing a thorough refactoring of things and it's not 100% ready yet. That is, API/names won't change from there, so it's safe to use and update, and it should at least allow you to ease PCGEx into your build pipeline.

**Comment by tychotic** [comment]
Thanks Tim - a good checkpoint for me would be when the example code
(specifically voronois + contours) are working, that's my only current
blocker.

Many thanks,
Matthew

**Comment by Nebukam** [comment]
Hey there @tychotic & @paulash :)
Merged the massive (228 commit ugh) branch to the main and tagged a [pre-release](https://github.com/Nebukam/PCGExtendedToolkit/tree/v0.16-preview.1) which hopefully will allow you to move forward.

Again, there iwas a tremendous lot of changes & refactors in this branch, it may introduce new bugs while some old ones are fixed, and will very likely break any existing graph. I've noticed that some updated nodes can cause crashes if they're not entierely deleted and recreated (Fuse cluster being one of those).

Also -- both voronoi & find contours have been updated 😬

I've checked in shipping on win64 and for what it's worth... "It WoRks On My MaChIne" ^^'

**Comment by mattmac-blv** [comment]
You’re an amazing human. I’ll give it a shake tomorrow.

**Comment by Nebukam** [comment]
Ahoy! I pushed another update that fixes a few bugs/problematic edge cases with Find Contours (amongst other things), tagged a [pre-release](https://github.com/Nebukam/PCGExtendedToolkit/releases/tag/v0.16-preview.2) with it.

Please let me know if you issues are fixed so I can close the two issues!

**Comment by Nebukam** [comment]
Closing since there hasn't been any news on this and the big update is live ;)

**Comment by Nebukam** [comment]
Sadly this is not on my end, Epic botched 5.5.4 for PCG and the issues you're seeing are only if you use the FAB version of the plugin with 5.5.4. You may either patch the editor (see https://discord.com/channels/1286108388471865406/1307157428324012072/1354125011040079976 on Discord) or ditch FAB and build the plugin from source :(

**Comment by penneydude** [comment]
Got it! Appreciate the quick response, thank you!

**Comment by Nebukam** [comment]
Basically my understanding is that FAB builds the plugin against the .0 patch of any minor version (so 5.5.0) and there's been a change in binary interfaces introduced with 5.5.4 which is why it's a non-issue when building from source (if you ignore the 45min additional build times) as opposed to FAB precompiled binaries; also explains why FAB build system doesn't pick up on the error.

Let me know if encounter any other issue when using source because if any those need fixing :D
