### ISSUE TITLE
virus in prebuilt installers?

### ISSUE THREAD

**Issue by tychotic** [Nebukam/PCGExtendedToolkit#84]
windows warns me of a "wacatac" virus in the 5.4 version of the download today 12/3. not sure if it's legit but figured I'd report it.

**Comment by Nebukam** [comment]
Did a bunch of scans the computer from which the packages have been uploaded is clean

**Comment by Nebukam** [comment]
@tychotic also there's no prebuilt installers, the archives only contains precompiled binaries for Windows by the Unreal Build Tool; if you get an .exe at any point that's not coming from here :D

**Comment by tychotic** [comment]
Ah, I was referring to the zip file, and I don't see anything too specific
in the output from Windows Defender. Including here for completeness: Quite
possible it's a false alarm, I don't really have any further diagnostics
but below is the particular object Windows is barking on.

[image: image.png]

**Comment by Nebukam** [comment]
The image hasn't been embedded 😅
I'm pretty sure it's a false positive, a quick look around google turns up a bunch of unreal threads where some SDK or another and plugins get flagged by windows defender with that specific threat over the years.

If you're worried I'd recommend building from source directly by cloning the repo -- I'll be closing this one as false positive for now.

Worst case scenario something infected the .zip during download or on your end; I'd recommend a full system scan just to be sure.

**Comment by tychotic** [comment]
Ah, thank you, and sorry for the false positive Not surprising!

I'm actually just setting up a new machine over here. Seems like I run into
something like this with unreal projects every time I do a new machine?


Anyway, question for you: is there a 5.4 version of the examples
project anywhere? There's some great debug code in there but I'm stuck on
5.4 for another few weeks.

Thanks
Matt
